name: microservicedocker

volumes:
  postgres-data:
    driver: local

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "9000:8080"
    networks:
      - frontend
      - backend

  webapi1:
    image: ${DOCKER_REGISTRY-}webapi1
    build:
      context: .
      dockerfile: WebApi1/Dockerfile
    ports:
      - "9001:8080"
    networks:
      - backend

  webapi2:
    image: ${DOCKER_REGISTRY-}webapi2
    build:
      context: .
      dockerfile: WebApi2/Dockerfile
    ports:
      - "9002:8080"
    networks:
      - backend

  # blazorapp:
  #   image: ${DOCKER_REGISTRY-}blazorapp
  #   build:
  #     context: .
  #     dockerfile: BlazorApp/BlazorApp/Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - frontend
